services:
  web:
    # собираем образ из Dockerfile
    build: .

    # пробрасываем порт на хост
    ports:
      - "5000:5000"

    # передаём порт в приложение
    environment:
      - APP_PORT=5000

    # web зависит от redis
    depends_on:
      - redis

  redis:
    # готовый образ Redis
    image: redis:7-alpine
